# Base configuration for SkyNet

:defaults: &defaults
  :repository: 'https://github.com/coshx/skynet'
  :builder: 'Static'
  :builder_options:
    :source: 'public'
    :destination: 'public'

:development:
  <<: *defaults
  :repository: 'https://github.com/rahearn/skynet'

:production:
  <<: *defaults
