# Base configuration for SkyNet

:defaults: &defaults
  :repository: 'https://github.com/coshx/skynet'
  :builder: 'Static'

:development:
  <<: *defaults
  :repository: 'https://github.com/rahearn/skynet'

:production:
  <<: *defaults
